// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB56XMV7VvlUxTUbjKongE2NE0gBkFc-Uc',
    appId: '1:908872962434:android:c39181e4a7a16220613f9b',
    messagingSenderId: '908872962434',
    projectId: 'planetsbrand-1f283',
    storageBucket: 'planetsbrand-1f283.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAkLckQSDzOPIaGvndlZx4OH8pbCeg67U',
    appId: '1:908872962434:ios:e09961d8b6e8bfe4613f9b',
    messagingSenderId: '908872962434',
    projectId: 'planetsbrand-1f283',
    storageBucket: 'planetsbrand-1f283.firebasestorage.app',
    androidClientId: '908872962434-kbo9m58aqat57dlmpj0snq1gjmgm859f.apps.googleusercontent.com',
    iosClientId: '908872962434-j4jo4id6ckrmvbe3d2ogubmtg7eqbum6.apps.googleusercontent.com',
    iosBundleId: 'com.planets.planetsbrand',
  );

}